task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # img_folder: /home/waas/DEIM/dataset/train/images
    # ann_file: /home/waas/DEIM/dataset/train/annotations/data.json
    img_folder: /root/workspace/VisDrone2019-DET-train
    ann_file: /root/workspace/coco_json/train.json
    # img_folder: /root/code/project/DEIM/dataset/train/images
    # ann_file: /root/code/project/DEIM/dataset/train/annotations/data.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction


# val_dataloader:
#   type: DataLoader
#   dataset:
#     type: CocoDetection
#     # img_folder: /home/waas/DEIM/dataset/val/images
#     # ann_file: /home/waas/DEIM/dataset/val/annotations/data.json
#     img_folder: /root/workspace/VisDrone2019-DET-val
#     ann_file: /root/workspace/coco_json/val.json
#     # img_folder: /root/code/project/DEIM/dataset/val/images
#     # ann_file: /root/code/project/DEIM/dataset/val/annotations/data.json
#     return_masks: False
#     transforms:
#       type: Compose
#       ops: ~
#   shuffle: False
#   num_workers: 4
#   drop_last: False
#   pin_memory: True
#   collate_fn:
#     type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/workspace/VisDrone2019-DET-test-dev
    ann_file: /root/workspace/coco_json/test_dev.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction